### ISSUE TITLE
[PROFILES] Improve topic design

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#174]
## Description
We have improved designs.

## Screenshots
<img width="753" alt="screen shot 2018-07-10 at 01 38 35" src="https://user-images.githubusercontent.com/877919/42480576-e1e7cb8e-83e6-11e8-8cb5-410db531e303.png">

## Files
- https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b435f7ade2a625665655996

## Tasks
- [x] Improve look and feel according to designs

**Comment by mtuchi** [comment]
**Describe the bug**
The listed topics have inconsistency `border-bottom`

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Country profile'
2. Click on 'Sidebar topic sections'
4. See 'inconsistency border bottom for some of the topic 

**Expected behavior**
Inconsistency `boder-bottom` in the sidebar topic section 

**Screenshots**
![inco](https://user-images.githubusercontent.com/6592749/42502870-cf795d24-843f-11e8-92d9-2e239a7a8ad3.png)


**Desktop (please complete the following information):**
 - OS: [e.g. Bunsen labs]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 67.0.3396.99]

@tebajanga

**Comment by kilemensi** [comment]
Fixed by  #178
